# Generated by Django 5.0.7 on 2024-07-31 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twik',
            name='text',
            field=models.TextField(max_length=150),
        ),
    ]
